# fly.toml app configuration file generated for dockfilesxyz on 2023-10-15T10:56:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dockfilesxyz"
primary_region = "sea"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
